var profile = {
  "name": "numchin",
  "image":
      "https://img.freepik.com/free-vector/floating-egg-fried-with-pan-cartoon-vector-icon-illustration-food-object-icon-concept-isolated-premium-vector-flat-cartoon-style_138676-3815.jpg?w=740&t=st=1648738512~exp=1648739112~hmac=4da584e057bb984f32eb5b8c2b498c6d5ee985bd697d165c678fa3e6b91e20fd",
  "email": "@gmail.com"
};

List recommends = [
  {
    "id": 105,
    "name": "โครงการกิจกรรม",
    "year": "2020",
    "term": "1",
    "sdate": "1/2/2563",
    "fdate": "2/2/2563",
    "tttime": "3 : 30",
    "approver": "อาจารย์คนที่ 1",
    "venue": "หอประชุมอาจารย์",
    "detail": "กิจกรรมที่ 1",
    "AJ": "อาจารย์ผู้อนุมัติ",
    "status": "อนุมัติ",
    "color": "#B6FFCE",
  },
  {
    "id": 106,
    "name": "โครงการกิจกรรม",
    "year": "2020",
    "term": "1",
    "sdate": "1/2/2563",
    "fdate": "2/2/2563",
    "tttime": "3 : 30",
    "approver": "อาจารย์คนที่ 2",
    "venue": "ห้องประชุมภาควิชาคณิตศาสตร์",
    "detail": "กิจกรรมที่ 2",
    "AJ": "อาจารย์ผู้อนุมัติ",
    "status": "อนุมัติ",
    "color": "#B6FFCE",
  },
  {
    "id": 107,
    "name": "โครงการกิจกรรม",
    "year": "2020",
    "term": "1",
    "sdate": "1/2/2563",
    "fdate": "2/2/2563",
    "tttime": "3 : 30",
    "approver": "อาจารย์คนที่ 3",
    "venue": "ตึก K",
    "detail": "กิจกรรมที่ 3",
    "AJ": "อาจารย์ผู้อนุมัติ",
    "status": "อนุมัติ",
    "color": "#B6FFCE",
  },
  {
    "id": 108,
    "name": "โครงการกิจกรรม",
    "year": "2020",
    "term": "1",
    "sdate": "1/2/2563",
    "fdate": "2/2/2563",
    "tttime": "3 : 30",
    "approver": "อาจารย์คนที่ 4",
    "venue": "หอประชุมอาจารย์",
    "detail": "กิจกรรมที่ 4",
    "AJ": "อาจารย์ผู้อนุมัติ",
    "status": "อนุมัติ",
    "color": "#B6FFCE",
  },
  {
    "id": 109,
    "name": "โครงการกิจกรรม",
    "year": "2020",
    "term": "1",
    "sdate": "1/2/2563",
    "fdate": "2/2/2563",
    "tttime": "3 : 30",
    "approver": "อาจารย์คนที่ 5",
    "venue": "หอประชุมอาจารย์",
    "detail": "กิจกรรมที่ 5",
    "AJ": "อาจารย์ผู้อนุมัติ",
    "status": "อนุมัติ",
    "color": "#B6FFCE",
  }
];
